version: '3.8'

volumes:
  dragonfly_data:

# Service that can be used for testing the adapters
services:
  memcached:
    image: "memcached:alpine"
    ports:
        - "11211:11211"

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
    command: "--name nats"

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6380:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    volumes:
      - dragonfly_data:/data